language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'grunt-unified-manifest' ]; then cd .. && eval "mv $currentfolder grunt-unified-manifest" && cd grunt-unified-manifest; fi

